name = "chat-interface"
component_path = "/nix/store/hc8vhd5b90himrdgg8gj3ncnnbagz3qc-chat-interface-0.1.0/lib/chat-interface.wasm"
short_description = "An HTTP server actor with REST API and WebSocket support"

[[handlers]]
type = "runtime"

[handlers.config]

[[handlers]]
type = "http-framework"

[handlers.config]

[[handlers]]
type = "timing"

[handlers.config]
max_sleep_duration = 3600000
min_sleep_duration = 1

[[handlers]]
type = "supervisor"

[handlers.config]
