name = "chat-interface"
component_path = "/nix/store/rn75z7xi98aafi3cgh4h491f7w1466jf-chat-interface-0.1.0/lib/component.wasm"
short_description = "An HTTP server actor with REST API and WebSocket support"
init_state = "/Users/colinrozzi/work/actor-registry/chat-interface/init.json"

[[handlers]]
type = "runtime"

[handlers.config]

[[handlers]]
type = "http-framework"

[handlers.config]

[[handlers]]
type = "timing"

[handlers.config]
max_sleep_duration = 3600000
min_sleep_duration = 1

[[handlers]]
type = "supervisor"

[handlers.config]

[[handlers]]
type = "store"

[handlers.config]
