package ntwk:theater;

world chat-interface {
    import runtime;
    import http-framework;
    import http-client;
    import websocket-types;
    import supervisor;
    import timing;
    import message-server-host;
    import store;

    export message-server-client;
    export actor;
    export http-handlers;
    export supervisor-handlers;
}
